plugins { id 'com.android.application' }

android {
    namespace = 'net.shadownet.shadowvpn.android'
    compileSdk = 35
    defaultConfig {
        applicationId = 'net.shadownet.shadowvpn.android'
        minSdk = 29
        targetSdk = 35
        versionCode = 17
        versionName = '0.15.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { implementation files('libs/shadowvpn-core.aar') }
