plugins { id 'com.android.application' }

android {
    namespace = 'net.shadownet.shadowvpn.android'
    compileSdk = 35
    defaultConfig {
        applicationId = 'net.shadownet.shadowvpn.android'
        minSdk = 29
        targetSdk = 35
        versionCode = 18
        versionName = '0.16.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies { implementation files('libs/shadowvpn-core.aar') }
